# Generated by Django 5.1.1 on 2024-10-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0002_cartype_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='year',
        ),
    ]
